### ISSUE TITLE
Update to ppa:ondrej/php

### ISSUE THREAD

**Issue by Brunty** [phansible/role-php#10]
Hi,

I'm looking at putting in a PR for updating this to use `ppa:ondrej/php` - this will require changes to the way the `php_version`, `php_config_prefix` and `php.packages` variables are handled.

I've opened this issue to discuss some possible ways to handle it, as I'm not yet familiar with how the phansible web app interacts with the role to produce the final bundle at the end.

I was thinking of something along the lines of the following:

```
php_version: 5.6
php:
    ppa: "php"
    packages: ["php{{ php_version }}-cli", "php{{ php_version }}-intl", "php{{ php_version }}-mcrypt"]

php_config_prefix: "/etc/php/{{ php_version }}"
```

But thought I'd open up a discussion around how it could (_should_ ?) be handled, or how you'd like it handled for phansible.
